apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactquestionweb
spec:
  selector:
    matchLabels:
      app: reactquestionweb
  template:
    metadata:
      labels:
        app: reactquestionweb
    spec:
      containers:
        - name: reactquestionweb
          image: reactquestionweb
          resources:
            limits:
              memory: "20Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactquestionweb
spec:
  selector:
    app: reactquestionweb
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactquestionweb
  labels:
    name: reactquestionweb
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: reactquestionweb
                port:
                  number: 80
